name: Lawyer
favicon: null
layout_spectrum: 0.88536
typography_spectrum: 0.06454
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#00a5e2'
    - '#6b6b6b'
    - '#5ec4ea'
  brandStrength: 0.25
  lightness: 0.0625
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
